# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BlendData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBlendData(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BlendData()
        x.Init(buf, n + offset)
        return x

    # BlendData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BlendData
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BlendData
    def InfoList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from FlatData.BlendInfo import BlendInfo
            obj = BlendInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BlendData
    def InfoListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BlendData
    def InfoListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def BlendDataStart(builder): builder.StartObject(2)
def BlendDataAddType(builder, Type): builder.PrependInt32Slot(0, Type, 0)
def BlendDataAddInfoList(builder, InfoList): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(InfoList), 0)
def BlendDataStartInfoListVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def BlendDataEnd(builder): return builder.EndObject()
