# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CharacterDialogSubtitleExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCharacterDialogSubtitleExcel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CharacterDialogSubtitleExcel()
        x.Init(buf, n + offset)
        return x

    # CharacterDialogSubtitleExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CharacterDialogSubtitleExcel
    def LocalizeCVGroup(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterDialogSubtitleExcel
    def CharacterId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # CharacterDialogSubtitleExcel
    def Duration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # CharacterDialogSubtitleExcel
    def DurationKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # CharacterDialogSubtitleExcel
    def Separate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CharacterDialogSubtitleExcel
    def LocalizeKR(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterDialogSubtitleExcel
    def LocalizeJP(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterDialogSubtitleExcel
    def LocalizeTH(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterDialogSubtitleExcel
    def LocalizeTW(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterDialogSubtitleExcel
    def LocalizeEN(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def CharacterDialogSubtitleExcelStart(builder): builder.StartObject(10)
def CharacterDialogSubtitleExcelAddLocalizeCVGroup(builder, LocalizeCVGroup): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(LocalizeCVGroup), 0)
def CharacterDialogSubtitleExcelAddCharacterId(builder, CharacterId): builder.PrependInt64Slot(1, CharacterId, 0)
def CharacterDialogSubtitleExcelAddDuration(builder, Duration): builder.PrependInt64Slot(2, Duration, 0)
def CharacterDialogSubtitleExcelAddDurationKr(builder, DurationKr): builder.PrependInt64Slot(3, DurationKr, 0)
def CharacterDialogSubtitleExcelAddSeparate(builder, Separate): builder.PrependBoolSlot(4, Separate, 0)
def CharacterDialogSubtitleExcelAddLocalizeKR(builder, LocalizeKR): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(LocalizeKR), 0)
def CharacterDialogSubtitleExcelAddLocalizeJP(builder, LocalizeJP): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(LocalizeJP), 0)
def CharacterDialogSubtitleExcelAddLocalizeTH(builder, LocalizeTH): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(LocalizeTH), 0)
def CharacterDialogSubtitleExcelAddLocalizeTW(builder, LocalizeTW): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(LocalizeTW), 0)
def CharacterDialogSubtitleExcelAddLocalizeEN(builder, LocalizeEN): builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(LocalizeEN), 0)
def CharacterDialogSubtitleExcelEnd(builder): return builder.EndObject()
