# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ClanChattingEmojiExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsClanChattingEmojiExcel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ClanChattingEmojiExcel()
        x.Init(buf, n + offset)
        return x

    # ClanChattingEmojiExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ClanChattingEmojiExcel
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ClanChattingEmojiExcel
    def TabGroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ClanChattingEmojiExcel
    def DisplayOrder(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ClanChattingEmojiExcel
    def ImagePathKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ClanChattingEmojiExcel
    def ImagePathJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ClanChattingEmojiExcel
    def ImagePathTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ClanChattingEmojiExcel
    def ImagePathTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ClanChattingEmojiExcel
    def ImagePathEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ClanChattingEmojiExcelStart(builder): builder.StartObject(8)
def ClanChattingEmojiExcelAddId(builder, Id): builder.PrependInt64Slot(0, Id, 0)
def ClanChattingEmojiExcelAddTabGroupId(builder, TabGroupId): builder.PrependInt32Slot(1, TabGroupId, 0)
def ClanChattingEmojiExcelAddDisplayOrder(builder, DisplayOrder): builder.PrependInt32Slot(2, DisplayOrder, 0)
def ClanChattingEmojiExcelAddImagePathKr(builder, ImagePathKr): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(ImagePathKr), 0)
def ClanChattingEmojiExcelAddImagePathJp(builder, ImagePathJp): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(ImagePathJp), 0)
def ClanChattingEmojiExcelAddImagePathTh(builder, ImagePathTh): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(ImagePathTh), 0)
def ClanChattingEmojiExcelAddImagePathTw(builder, ImagePathTw): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(ImagePathTw), 0)
def ClanChattingEmojiExcelAddImagePathEn(builder, ImagePathEn): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(ImagePathEn), 0)
def ClanChattingEmojiExcelEnd(builder): return builder.EndObject()
