# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ConquestErosionUnitExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsConquestErosionUnitExcel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ConquestErosionUnitExcel()
        x.Init(buf, n + offset)
        return x

    # ConquestErosionUnitExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ConquestErosionUnitExcel
    def TilePrefabId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConquestErosionUnitExcel
    def MassErosionUnitId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConquestErosionUnitExcel
    def MassErosionUnitRotationY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ConquestErosionUnitExcel
    def IndividualErosionUnitId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConquestErosionUnitExcel
    def IndividualErosionUnitRotationY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def ConquestErosionUnitExcelStart(builder): builder.StartObject(5)
def ConquestErosionUnitExcelAddTilePrefabId(builder, TilePrefabId): builder.PrependInt64Slot(0, TilePrefabId, 0)
def ConquestErosionUnitExcelAddMassErosionUnitId(builder, MassErosionUnitId): builder.PrependInt64Slot(1, MassErosionUnitId, 0)
def ConquestErosionUnitExcelAddMassErosionUnitRotationY(builder, MassErosionUnitRotationY): builder.PrependFloat32Slot(2, MassErosionUnitRotationY, 0.0)
def ConquestErosionUnitExcelAddIndividualErosionUnitId(builder, IndividualErosionUnitId): builder.PrependInt64Slot(3, IndividualErosionUnitId, 0)
def ConquestErosionUnitExcelAddIndividualErosionUnitRotationY(builder, IndividualErosionUnitRotationY): builder.PrependFloat32Slot(4, IndividualErosionUnitRotationY, 0.0)
def ConquestErosionUnitExcelEnd(builder): return builder.EndObject()
