# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventContentSpoilerPopupExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsEventContentSpoilerPopupExcel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventContentSpoilerPopupExcel()
        x.Init(buf, n + offset)
        return x

    # EventContentSpoilerPopupExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventContentSpoilerPopupExcel
    def EventContentId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentSpoilerPopupExcel
    def SpoilerPopupTitle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EventContentSpoilerPopupExcel
    def SpoilerPopupDescription(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EventContentSpoilerPopupExcel
    def IsWarningPopUp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # EventContentSpoilerPopupExcel
    def ConditionScenarioModeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def EventContentSpoilerPopupExcelStart(builder): builder.StartObject(5)
def EventContentSpoilerPopupExcelAddEventContentId(builder, EventContentId): builder.PrependInt64Slot(0, EventContentId, 0)
def EventContentSpoilerPopupExcelAddSpoilerPopupTitle(builder, SpoilerPopupTitle): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(SpoilerPopupTitle), 0)
def EventContentSpoilerPopupExcelAddSpoilerPopupDescription(builder, SpoilerPopupDescription): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(SpoilerPopupDescription), 0)
def EventContentSpoilerPopupExcelAddIsWarningPopUp(builder, IsWarningPopUp): builder.PrependBoolSlot(3, IsWarningPopUp, 0)
def EventContentSpoilerPopupExcelAddConditionScenarioModeId(builder, ConditionScenarioModeId): builder.PrependInt64Slot(4, ConditionScenarioModeId, 0)
def EventContentSpoilerPopupExcelEnd(builder): return builder.EndObject()
