# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventContentTreasureExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsEventContentTreasureExcel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventContentTreasureExcel()
        x.Init(buf, n + offset)
        return x

    # EventContentTreasureExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventContentTreasureExcel
    def EventContentId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentTreasureExcel
    def TitleLocalize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EventContentTreasureExcel
    def LoopRound(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventContentTreasureExcel
    def UsePrefabName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EventContentTreasureExcel
    def TreasureBGImagePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def EventContentTreasureExcelStart(builder): builder.StartObject(5)
def EventContentTreasureExcelAddEventContentId(builder, EventContentId): builder.PrependInt64Slot(0, EventContentId, 0)
def EventContentTreasureExcelAddTitleLocalize(builder, TitleLocalize): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(TitleLocalize), 0)
def EventContentTreasureExcelAddLoopRound(builder, LoopRound): builder.PrependInt32Slot(2, LoopRound, 0)
def EventContentTreasureExcelAddUsePrefabName(builder, UsePrefabName): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(UsePrefabName), 0)
def EventContentTreasureExcelAddTreasureBGImagePath(builder, TreasureBGImagePath): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(TreasureBGImagePath), 0)
def EventContentTreasureExcelEnd(builder): return builder.EndObject()
