# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventContentChangeExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsEventContentChangeExcel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventContentChangeExcel()
        x.Init(buf, n + offset)
        return x

    # EventContentChangeExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventContentChangeExcel
    def EventContentId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentChangeExcel
    def ChangeCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentChangeExcel
    def IsLast(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # EventContentChangeExcel
    def RewardParcelType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventContentChangeExcel
    def RewardId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentChangeExcel
    def RewardAmount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventContentChangeExcel
    def ChangeCostType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventContentChangeExcel
    def ChangeCostId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentChangeExcel
    def ChangeCostAmount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def EventContentChangeExcelStart(builder): builder.StartObject(9)
def EventContentChangeExcelAddEventContentId(builder, EventContentId): builder.PrependInt64Slot(0, EventContentId, 0)
def EventContentChangeExcelAddChangeCount(builder, ChangeCount): builder.PrependInt64Slot(1, ChangeCount, 0)
def EventContentChangeExcelAddIsLast(builder, IsLast): builder.PrependBoolSlot(2, IsLast, 0)
def EventContentChangeExcelAddRewardParcelType(builder, RewardParcelType): builder.PrependInt32Slot(3, RewardParcelType, 0)
def EventContentChangeExcelAddRewardId(builder, RewardId): builder.PrependInt64Slot(4, RewardId, 0)
def EventContentChangeExcelAddRewardAmount(builder, RewardAmount): builder.PrependInt32Slot(5, RewardAmount, 0)
def EventContentChangeExcelAddChangeCostType(builder, ChangeCostType): builder.PrependInt32Slot(6, ChangeCostType, 0)
def EventContentChangeExcelAddChangeCostId(builder, ChangeCostId): builder.PrependInt64Slot(7, ChangeCostId, 0)
def EventContentChangeExcelAddChangeCostAmount(builder, ChangeCostAmount): builder.PrependInt32Slot(8, ChangeCostAmount, 0)
def EventContentChangeExcelEnd(builder): return builder.EndObject()
