# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventContentTreasureRoundExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsEventContentTreasureRoundExcel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventContentTreasureRoundExcel()
        x.Init(buf, n + offset)
        return x

    # EventContentTreasureRoundExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventContentTreasureRoundExcel
    def EventContentId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentTreasureRoundExcel
    def TreasureRound(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventContentTreasureRoundExcel
    def TreasureRoundSize(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # EventContentTreasureRoundExcel
    def TreasureRoundSizeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # EventContentTreasureRoundExcel
    def TreasureRoundSizeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EventContentTreasureRoundExcel
    def TreasureRoundSizeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # EventContentTreasureRoundExcel
    def CellVisualSortUnstructed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # EventContentTreasureRoundExcel
    def CellCheckGoodsId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentTreasureRoundExcel
    def CellRewardId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentTreasureRoundExcel
    def RewardID(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # EventContentTreasureRoundExcel
    def RewardIDAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # EventContentTreasureRoundExcel
    def RewardIDLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EventContentTreasureRoundExcel
    def RewardIDIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # EventContentTreasureRoundExcel
    def RewardAmount(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # EventContentTreasureRoundExcel
    def RewardAmountAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # EventContentTreasureRoundExcel
    def RewardAmountLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EventContentTreasureRoundExcel
    def RewardAmountIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # EventContentTreasureRoundExcel
    def TreasureCellImagePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def EventContentTreasureRoundExcelStart(builder): builder.StartObject(9)
def EventContentTreasureRoundExcelAddEventContentId(builder, EventContentId): builder.PrependInt64Slot(0, EventContentId, 0)
def EventContentTreasureRoundExcelAddTreasureRound(builder, TreasureRound): builder.PrependInt32Slot(1, TreasureRound, 0)
def EventContentTreasureRoundExcelAddTreasureRoundSize(builder, TreasureRoundSize): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(TreasureRoundSize), 0)
def EventContentTreasureRoundExcelStartTreasureRoundSizeVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def EventContentTreasureRoundExcelAddCellVisualSortUnstructed(builder, CellVisualSortUnstructed): builder.PrependBoolSlot(3, CellVisualSortUnstructed, 0)
def EventContentTreasureRoundExcelAddCellCheckGoodsId(builder, CellCheckGoodsId): builder.PrependInt64Slot(4, CellCheckGoodsId, 0)
def EventContentTreasureRoundExcelAddCellRewardId(builder, CellRewardId): builder.PrependInt64Slot(5, CellRewardId, 0)
def EventContentTreasureRoundExcelAddRewardID(builder, RewardID): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(RewardID), 0)
def EventContentTreasureRoundExcelStartRewardIDVector(builder, numElems): return builder.StartVector(8, numElems, 8)
def EventContentTreasureRoundExcelAddRewardAmount(builder, RewardAmount): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(RewardAmount), 0)
def EventContentTreasureRoundExcelStartRewardAmountVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def EventContentTreasureRoundExcelAddTreasureCellImagePath(builder, TreasureCellImagePath): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(TreasureCellImagePath), 0)
def EventContentTreasureRoundExcelEnd(builder): return builder.EndObject()
