# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventContentBoxGachaManageExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsEventContentBoxGachaManageExcel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventContentBoxGachaManageExcel()
        x.Init(buf, n + offset)
        return x

    # EventContentBoxGachaManageExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventContentBoxGachaManageExcel
    def EventContentId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentBoxGachaManageExcel
    def Round(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentBoxGachaManageExcel
    def GoodsId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentBoxGachaManageExcel
    def IsLoop(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def EventContentBoxGachaManageExcelStart(builder): builder.StartObject(4)
def EventContentBoxGachaManageExcelAddEventContentId(builder, EventContentId): builder.PrependInt64Slot(0, EventContentId, 0)
def EventContentBoxGachaManageExcelAddRound(builder, Round): builder.PrependInt64Slot(1, Round, 0)
def EventContentBoxGachaManageExcelAddGoodsId(builder, GoodsId): builder.PrependInt64Slot(2, GoodsId, 0)
def EventContentBoxGachaManageExcelAddIsLoop(builder, IsLoop): builder.PrependBoolSlot(3, IsLoop, 0)
def EventContentBoxGachaManageExcelEnd(builder): return builder.EndObject()
