# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FieldMasteryManageExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFieldMasteryManageExcel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FieldMasteryManageExcel()
        x.Init(buf, n + offset)
        return x

    # FieldMasteryManageExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FieldMasteryManageExcel
    def FieldSeason(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # FieldMasteryManageExcel
    def LocalizeEtc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FieldMasteryManageExcel
    def ImagePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FieldMasteryManageExcel
    def LevelId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def FieldMasteryManageExcelStart(builder): builder.StartObject(4)
def FieldMasteryManageExcelAddFieldSeason(builder, FieldSeason): builder.PrependInt64Slot(0, FieldSeason, 0)
def FieldMasteryManageExcelAddLocalizeEtc(builder, LocalizeEtc): builder.PrependUint32Slot(1, LocalizeEtc, 0)
def FieldMasteryManageExcelAddImagePath(builder, ImagePath): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(ImagePath), 0)
def FieldMasteryManageExcelAddLevelId(builder, LevelId): builder.PrependInt64Slot(3, LevelId, 0)
def FieldMasteryManageExcelEnd(builder): return builder.EndObject()
