# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GachaElementRecursiveExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGachaElementRecursiveExcel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GachaElementRecursiveExcel()
        x.Init(buf, n + offset)
        return x

    # GachaElementRecursiveExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GachaElementRecursiveExcel
    def ID(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # GachaElementRecursiveExcel
    def GachaGroupID(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # GachaElementRecursiveExcel
    def ParcelType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GachaElementRecursiveExcel
    def ParcelID(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # GachaElementRecursiveExcel
    def ParcelAmountMin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GachaElementRecursiveExcel
    def ParcelAmountMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GachaElementRecursiveExcel
    def Prob(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GachaElementRecursiveExcel
    def State(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def GachaElementRecursiveExcelStart(builder): builder.StartObject(8)
def GachaElementRecursiveExcelAddID(builder, ID): builder.PrependInt64Slot(0, ID, 0)
def GachaElementRecursiveExcelAddGachaGroupID(builder, GachaGroupID): builder.PrependInt64Slot(1, GachaGroupID, 0)
def GachaElementRecursiveExcelAddParcelType(builder, ParcelType): builder.PrependInt32Slot(2, ParcelType, 0)
def GachaElementRecursiveExcelAddParcelID(builder, ParcelID): builder.PrependInt64Slot(3, ParcelID, 0)
def GachaElementRecursiveExcelAddParcelAmountMin(builder, ParcelAmountMin): builder.PrependInt32Slot(4, ParcelAmountMin, 0)
def GachaElementRecursiveExcelAddParcelAmountMax(builder, ParcelAmountMax): builder.PrependInt32Slot(5, ParcelAmountMax, 0)
def GachaElementRecursiveExcelAddProb(builder, Prob): builder.PrependInt32Slot(6, Prob, 0)
def GachaElementRecursiveExcelAddState(builder, State): builder.PrependInt32Slot(7, State, 0)
def GachaElementRecursiveExcelEnd(builder): return builder.EndObject()
