# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HpBarAbbreviationExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsHpBarAbbreviationExcel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HpBarAbbreviationExcel()
        x.Init(buf, n + offset)
        return x

    # HpBarAbbreviationExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HpBarAbbreviationExcel
    def MonsterLv(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HpBarAbbreviationExcel
    def StandardHpBar(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HpBarAbbreviationExcel
    def RaidBossHpBar(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def HpBarAbbreviationExcelStart(builder): builder.StartObject(3)
def HpBarAbbreviationExcelAddMonsterLv(builder, MonsterLv): builder.PrependInt32Slot(0, MonsterLv, 0)
def HpBarAbbreviationExcelAddStandardHpBar(builder, StandardHpBar): builder.PrependInt32Slot(1, StandardHpBar, 0)
def HpBarAbbreviationExcelAddRaidBossHpBar(builder, RaidBossHpBar): builder.PrependInt32Slot(2, RaidBossHpBar, 0)
def HpBarAbbreviationExcelEnd(builder): return builder.EndObject()
