# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class IdCardBackgroundExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsIdCardBackgroundExcel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IdCardBackgroundExcel()
        x.Init(buf, n + offset)
        return x

    # IdCardBackgroundExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IdCardBackgroundExcel
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # IdCardBackgroundExcel
    def Rarity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # IdCardBackgroundExcel
    def DisplayOrder(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # IdCardBackgroundExcel
    def CollectionVisible(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # IdCardBackgroundExcel
    def IsDefault(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # IdCardBackgroundExcel
    def BgPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # IdCardBackgroundExcel
    def LocalizeEtcId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # IdCardBackgroundExcel
    def Icon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def IdCardBackgroundExcelStart(builder): builder.StartObject(8)
def IdCardBackgroundExcelAddId(builder, Id): builder.PrependInt64Slot(0, Id, 0)
def IdCardBackgroundExcelAddRarity(builder, Rarity): builder.PrependInt32Slot(1, Rarity, 0)
def IdCardBackgroundExcelAddDisplayOrder(builder, DisplayOrder): builder.PrependInt64Slot(2, DisplayOrder, 0)
def IdCardBackgroundExcelAddCollectionVisible(builder, CollectionVisible): builder.PrependBoolSlot(3, CollectionVisible, 0)
def IdCardBackgroundExcelAddIsDefault(builder, IsDefault): builder.PrependBoolSlot(4, IsDefault, 0)
def IdCardBackgroundExcelAddBgPath(builder, BgPath): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(BgPath), 0)
def IdCardBackgroundExcelAddLocalizeEtcId(builder, LocalizeEtcId): builder.PrependUint32Slot(6, LocalizeEtcId, 0)
def IdCardBackgroundExcelAddIcon(builder, Icon): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(Icon), 0)
def IdCardBackgroundExcelEnd(builder): return builder.EndObject()
