# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LocalizeCharProfileExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsLocalizeCharProfileExcel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LocalizeCharProfileExcel()
        x.Init(buf, n + offset)
        return x

    # LocalizeCharProfileExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LocalizeCharProfileExcel
    def CharacterId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # LocalizeCharProfileExcel
    def StatusMessageKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def StatusMessageJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def StatusMessageTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def StatusMessageTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def StatusMessageEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def FullNameKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def FullNameJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def FullNameTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def FullNameTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def FullNameEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def FamilyNameKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def FamilyNameRubyKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def PersonalNameKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def PersonalNameRubyKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def FamilyNameJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def FamilyNameRubyJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def PersonalNameJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def PersonalNameRubyJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def FamilyNameTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def FamilyNameRubyTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def PersonalNameTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def PersonalNameRubyTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def FamilyNameTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def FamilyNameRubyTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def PersonalNameTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def PersonalNameRubyTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def FamilyNameEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def FamilyNameRubyEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def PersonalNameEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def PersonalNameRubyEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def SchoolYearKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def SchoolYearJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def SchoolYearTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def SchoolYearTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(72))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def SchoolYearEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(74))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def CharacterAgeKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(76))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def CharacterAgeJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(78))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def CharacterAgeTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(80))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def CharacterAgeTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(82))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def CharacterAgeEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(84))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def BirthDay(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(86))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def BirthdayKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(88))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def BirthdayJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(90))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def BirthdayTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(92))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def BirthdayTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(94))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def BirthdayEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(96))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def CharHeightKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(98))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def CharHeightJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(100))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def CharHeightTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(102))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def CharHeightTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(104))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def CharHeightEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(106))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def DesignerNameKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(108))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def DesignerNameJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(110))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def DesignerNameTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(112))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def DesignerNameTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(114))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def DesignerNameEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(116))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def IllustratorNameKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(118))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def IllustratorNameJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(120))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def IllustratorNameTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(122))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def IllustratorNameTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(124))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def IllustratorNameEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(126))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def CharacterVoiceKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(128))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def CharacterVoiceJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(130))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def CharacterVoiceTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(132))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def CharacterVoiceTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(134))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def CharacterVoiceEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(136))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def KRCharacterVoiceKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(138))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def KRCharacterVoiceTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(140))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def KRCharacterVoiceTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(142))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def KRCharacterVoiceEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(144))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def HobbyKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(146))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def HobbyJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(148))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def HobbyTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(150))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def HobbyTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(152))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def HobbyEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(154))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def WeaponNameKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(156))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def WeaponDescKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(158))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def WeaponNameJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(160))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def WeaponDescJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(162))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def WeaponNameTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(164))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def WeaponDescTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(166))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def WeaponNameTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(168))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def WeaponDescTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(170))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def WeaponNameEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(172))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def WeaponDescEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(174))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def ProfileIntroductionKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(176))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def ProfileIntroductionJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(178))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def ProfileIntroductionTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(180))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def ProfileIntroductionTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(182))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def ProfileIntroductionEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(184))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def CharacterSSRNewKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(186))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def CharacterSSRNewJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(188))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def CharacterSSRNewTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(190))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def CharacterSSRNewTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(192))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeCharProfileExcel
    def CharacterSSRNewEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(194))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def LocalizeCharProfileExcelStart(builder): builder.StartObject(96)
def LocalizeCharProfileExcelAddCharacterId(builder, CharacterId): builder.PrependInt64Slot(0, CharacterId, 0)
def LocalizeCharProfileExcelAddStatusMessageKr(builder, StatusMessageKr): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(StatusMessageKr), 0)
def LocalizeCharProfileExcelAddStatusMessageJp(builder, StatusMessageJp): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(StatusMessageJp), 0)
def LocalizeCharProfileExcelAddStatusMessageTh(builder, StatusMessageTh): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(StatusMessageTh), 0)
def LocalizeCharProfileExcelAddStatusMessageTw(builder, StatusMessageTw): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(StatusMessageTw), 0)
def LocalizeCharProfileExcelAddStatusMessageEn(builder, StatusMessageEn): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(StatusMessageEn), 0)
def LocalizeCharProfileExcelAddFullNameKr(builder, FullNameKr): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(FullNameKr), 0)
def LocalizeCharProfileExcelAddFullNameJp(builder, FullNameJp): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(FullNameJp), 0)
def LocalizeCharProfileExcelAddFullNameTh(builder, FullNameTh): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(FullNameTh), 0)
def LocalizeCharProfileExcelAddFullNameTw(builder, FullNameTw): builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(FullNameTw), 0)
def LocalizeCharProfileExcelAddFullNameEn(builder, FullNameEn): builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(FullNameEn), 0)
def LocalizeCharProfileExcelAddFamilyNameKr(builder, FamilyNameKr): builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(FamilyNameKr), 0)
def LocalizeCharProfileExcelAddFamilyNameRubyKr(builder, FamilyNameRubyKr): builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(FamilyNameRubyKr), 0)
def LocalizeCharProfileExcelAddPersonalNameKr(builder, PersonalNameKr): builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(PersonalNameKr), 0)
def LocalizeCharProfileExcelAddPersonalNameRubyKr(builder, PersonalNameRubyKr): builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(PersonalNameRubyKr), 0)
def LocalizeCharProfileExcelAddFamilyNameJp(builder, FamilyNameJp): builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(FamilyNameJp), 0)
def LocalizeCharProfileExcelAddFamilyNameRubyJp(builder, FamilyNameRubyJp): builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(FamilyNameRubyJp), 0)
def LocalizeCharProfileExcelAddPersonalNameJp(builder, PersonalNameJp): builder.PrependUOffsetTRelativeSlot(17, flatbuffers.number_types.UOffsetTFlags.py_type(PersonalNameJp), 0)
def LocalizeCharProfileExcelAddPersonalNameRubyJp(builder, PersonalNameRubyJp): builder.PrependUOffsetTRelativeSlot(18, flatbuffers.number_types.UOffsetTFlags.py_type(PersonalNameRubyJp), 0)
def LocalizeCharProfileExcelAddFamilyNameTh(builder, FamilyNameTh): builder.PrependUOffsetTRelativeSlot(19, flatbuffers.number_types.UOffsetTFlags.py_type(FamilyNameTh), 0)
def LocalizeCharProfileExcelAddFamilyNameRubyTh(builder, FamilyNameRubyTh): builder.PrependUOffsetTRelativeSlot(20, flatbuffers.number_types.UOffsetTFlags.py_type(FamilyNameRubyTh), 0)
def LocalizeCharProfileExcelAddPersonalNameTh(builder, PersonalNameTh): builder.PrependUOffsetTRelativeSlot(21, flatbuffers.number_types.UOffsetTFlags.py_type(PersonalNameTh), 0)
def LocalizeCharProfileExcelAddPersonalNameRubyTh(builder, PersonalNameRubyTh): builder.PrependUOffsetTRelativeSlot(22, flatbuffers.number_types.UOffsetTFlags.py_type(PersonalNameRubyTh), 0)
def LocalizeCharProfileExcelAddFamilyNameTw(builder, FamilyNameTw): builder.PrependUOffsetTRelativeSlot(23, flatbuffers.number_types.UOffsetTFlags.py_type(FamilyNameTw), 0)
def LocalizeCharProfileExcelAddFamilyNameRubyTw(builder, FamilyNameRubyTw): builder.PrependUOffsetTRelativeSlot(24, flatbuffers.number_types.UOffsetTFlags.py_type(FamilyNameRubyTw), 0)
def LocalizeCharProfileExcelAddPersonalNameTw(builder, PersonalNameTw): builder.PrependUOffsetTRelativeSlot(25, flatbuffers.number_types.UOffsetTFlags.py_type(PersonalNameTw), 0)
def LocalizeCharProfileExcelAddPersonalNameRubyTw(builder, PersonalNameRubyTw): builder.PrependUOffsetTRelativeSlot(26, flatbuffers.number_types.UOffsetTFlags.py_type(PersonalNameRubyTw), 0)
def LocalizeCharProfileExcelAddFamilyNameEn(builder, FamilyNameEn): builder.PrependUOffsetTRelativeSlot(27, flatbuffers.number_types.UOffsetTFlags.py_type(FamilyNameEn), 0)
def LocalizeCharProfileExcelAddFamilyNameRubyEn(builder, FamilyNameRubyEn): builder.PrependUOffsetTRelativeSlot(28, flatbuffers.number_types.UOffsetTFlags.py_type(FamilyNameRubyEn), 0)
def LocalizeCharProfileExcelAddPersonalNameEn(builder, PersonalNameEn): builder.PrependUOffsetTRelativeSlot(29, flatbuffers.number_types.UOffsetTFlags.py_type(PersonalNameEn), 0)
def LocalizeCharProfileExcelAddPersonalNameRubyEn(builder, PersonalNameRubyEn): builder.PrependUOffsetTRelativeSlot(30, flatbuffers.number_types.UOffsetTFlags.py_type(PersonalNameRubyEn), 0)
def LocalizeCharProfileExcelAddSchoolYearKr(builder, SchoolYearKr): builder.PrependUOffsetTRelativeSlot(31, flatbuffers.number_types.UOffsetTFlags.py_type(SchoolYearKr), 0)
def LocalizeCharProfileExcelAddSchoolYearJp(builder, SchoolYearJp): builder.PrependUOffsetTRelativeSlot(32, flatbuffers.number_types.UOffsetTFlags.py_type(SchoolYearJp), 0)
def LocalizeCharProfileExcelAddSchoolYearTh(builder, SchoolYearTh): builder.PrependUOffsetTRelativeSlot(33, flatbuffers.number_types.UOffsetTFlags.py_type(SchoolYearTh), 0)
def LocalizeCharProfileExcelAddSchoolYearTw(builder, SchoolYearTw): builder.PrependUOffsetTRelativeSlot(34, flatbuffers.number_types.UOffsetTFlags.py_type(SchoolYearTw), 0)
def LocalizeCharProfileExcelAddSchoolYearEn(builder, SchoolYearEn): builder.PrependUOffsetTRelativeSlot(35, flatbuffers.number_types.UOffsetTFlags.py_type(SchoolYearEn), 0)
def LocalizeCharProfileExcelAddCharacterAgeKr(builder, CharacterAgeKr): builder.PrependUOffsetTRelativeSlot(36, flatbuffers.number_types.UOffsetTFlags.py_type(CharacterAgeKr), 0)
def LocalizeCharProfileExcelAddCharacterAgeJp(builder, CharacterAgeJp): builder.PrependUOffsetTRelativeSlot(37, flatbuffers.number_types.UOffsetTFlags.py_type(CharacterAgeJp), 0)
def LocalizeCharProfileExcelAddCharacterAgeTh(builder, CharacterAgeTh): builder.PrependUOffsetTRelativeSlot(38, flatbuffers.number_types.UOffsetTFlags.py_type(CharacterAgeTh), 0)
def LocalizeCharProfileExcelAddCharacterAgeTw(builder, CharacterAgeTw): builder.PrependUOffsetTRelativeSlot(39, flatbuffers.number_types.UOffsetTFlags.py_type(CharacterAgeTw), 0)
def LocalizeCharProfileExcelAddCharacterAgeEn(builder, CharacterAgeEn): builder.PrependUOffsetTRelativeSlot(40, flatbuffers.number_types.UOffsetTFlags.py_type(CharacterAgeEn), 0)
def LocalizeCharProfileExcelAddBirthDay(builder, BirthDay): builder.PrependUOffsetTRelativeSlot(41, flatbuffers.number_types.UOffsetTFlags.py_type(BirthDay), 0)
def LocalizeCharProfileExcelAddBirthdayKr(builder, BirthdayKr): builder.PrependUOffsetTRelativeSlot(42, flatbuffers.number_types.UOffsetTFlags.py_type(BirthdayKr), 0)
def LocalizeCharProfileExcelAddBirthdayJp(builder, BirthdayJp): builder.PrependUOffsetTRelativeSlot(43, flatbuffers.number_types.UOffsetTFlags.py_type(BirthdayJp), 0)
def LocalizeCharProfileExcelAddBirthdayTh(builder, BirthdayTh): builder.PrependUOffsetTRelativeSlot(44, flatbuffers.number_types.UOffsetTFlags.py_type(BirthdayTh), 0)
def LocalizeCharProfileExcelAddBirthdayTw(builder, BirthdayTw): builder.PrependUOffsetTRelativeSlot(45, flatbuffers.number_types.UOffsetTFlags.py_type(BirthdayTw), 0)
def LocalizeCharProfileExcelAddBirthdayEn(builder, BirthdayEn): builder.PrependUOffsetTRelativeSlot(46, flatbuffers.number_types.UOffsetTFlags.py_type(BirthdayEn), 0)
def LocalizeCharProfileExcelAddCharHeightKr(builder, CharHeightKr): builder.PrependUOffsetTRelativeSlot(47, flatbuffers.number_types.UOffsetTFlags.py_type(CharHeightKr), 0)
def LocalizeCharProfileExcelAddCharHeightJp(builder, CharHeightJp): builder.PrependUOffsetTRelativeSlot(48, flatbuffers.number_types.UOffsetTFlags.py_type(CharHeightJp), 0)
def LocalizeCharProfileExcelAddCharHeightTh(builder, CharHeightTh): builder.PrependUOffsetTRelativeSlot(49, flatbuffers.number_types.UOffsetTFlags.py_type(CharHeightTh), 0)
def LocalizeCharProfileExcelAddCharHeightTw(builder, CharHeightTw): builder.PrependUOffsetTRelativeSlot(50, flatbuffers.number_types.UOffsetTFlags.py_type(CharHeightTw), 0)
def LocalizeCharProfileExcelAddCharHeightEn(builder, CharHeightEn): builder.PrependUOffsetTRelativeSlot(51, flatbuffers.number_types.UOffsetTFlags.py_type(CharHeightEn), 0)
def LocalizeCharProfileExcelAddDesignerNameKr(builder, DesignerNameKr): builder.PrependUOffsetTRelativeSlot(52, flatbuffers.number_types.UOffsetTFlags.py_type(DesignerNameKr), 0)
def LocalizeCharProfileExcelAddDesignerNameJp(builder, DesignerNameJp): builder.PrependUOffsetTRelativeSlot(53, flatbuffers.number_types.UOffsetTFlags.py_type(DesignerNameJp), 0)
def LocalizeCharProfileExcelAddDesignerNameTh(builder, DesignerNameTh): builder.PrependUOffsetTRelativeSlot(54, flatbuffers.number_types.UOffsetTFlags.py_type(DesignerNameTh), 0)
def LocalizeCharProfileExcelAddDesignerNameTw(builder, DesignerNameTw): builder.PrependUOffsetTRelativeSlot(55, flatbuffers.number_types.UOffsetTFlags.py_type(DesignerNameTw), 0)
def LocalizeCharProfileExcelAddDesignerNameEn(builder, DesignerNameEn): builder.PrependUOffsetTRelativeSlot(56, flatbuffers.number_types.UOffsetTFlags.py_type(DesignerNameEn), 0)
def LocalizeCharProfileExcelAddIllustratorNameKr(builder, IllustratorNameKr): builder.PrependUOffsetTRelativeSlot(57, flatbuffers.number_types.UOffsetTFlags.py_type(IllustratorNameKr), 0)
def LocalizeCharProfileExcelAddIllustratorNameJp(builder, IllustratorNameJp): builder.PrependUOffsetTRelativeSlot(58, flatbuffers.number_types.UOffsetTFlags.py_type(IllustratorNameJp), 0)
def LocalizeCharProfileExcelAddIllustratorNameTh(builder, IllustratorNameTh): builder.PrependUOffsetTRelativeSlot(59, flatbuffers.number_types.UOffsetTFlags.py_type(IllustratorNameTh), 0)
def LocalizeCharProfileExcelAddIllustratorNameTw(builder, IllustratorNameTw): builder.PrependUOffsetTRelativeSlot(60, flatbuffers.number_types.UOffsetTFlags.py_type(IllustratorNameTw), 0)
def LocalizeCharProfileExcelAddIllustratorNameEn(builder, IllustratorNameEn): builder.PrependUOffsetTRelativeSlot(61, flatbuffers.number_types.UOffsetTFlags.py_type(IllustratorNameEn), 0)
def LocalizeCharProfileExcelAddCharacterVoiceKr(builder, CharacterVoiceKr): builder.PrependUOffsetTRelativeSlot(62, flatbuffers.number_types.UOffsetTFlags.py_type(CharacterVoiceKr), 0)
def LocalizeCharProfileExcelAddCharacterVoiceJp(builder, CharacterVoiceJp): builder.PrependUOffsetTRelativeSlot(63, flatbuffers.number_types.UOffsetTFlags.py_type(CharacterVoiceJp), 0)
def LocalizeCharProfileExcelAddCharacterVoiceTh(builder, CharacterVoiceTh): builder.PrependUOffsetTRelativeSlot(64, flatbuffers.number_types.UOffsetTFlags.py_type(CharacterVoiceTh), 0)
def LocalizeCharProfileExcelAddCharacterVoiceTw(builder, CharacterVoiceTw): builder.PrependUOffsetTRelativeSlot(65, flatbuffers.number_types.UOffsetTFlags.py_type(CharacterVoiceTw), 0)
def LocalizeCharProfileExcelAddCharacterVoiceEn(builder, CharacterVoiceEn): builder.PrependUOffsetTRelativeSlot(66, flatbuffers.number_types.UOffsetTFlags.py_type(CharacterVoiceEn), 0)
def LocalizeCharProfileExcelAddKRCharacterVoiceKr(builder, KRCharacterVoiceKr): builder.PrependUOffsetTRelativeSlot(67, flatbuffers.number_types.UOffsetTFlags.py_type(KRCharacterVoiceKr), 0)
def LocalizeCharProfileExcelAddKRCharacterVoiceTh(builder, KRCharacterVoiceTh): builder.PrependUOffsetTRelativeSlot(68, flatbuffers.number_types.UOffsetTFlags.py_type(KRCharacterVoiceTh), 0)
def LocalizeCharProfileExcelAddKRCharacterVoiceTw(builder, KRCharacterVoiceTw): builder.PrependUOffsetTRelativeSlot(69, flatbuffers.number_types.UOffsetTFlags.py_type(KRCharacterVoiceTw), 0)
def LocalizeCharProfileExcelAddKRCharacterVoiceEn(builder, KRCharacterVoiceEn): builder.PrependUOffsetTRelativeSlot(70, flatbuffers.number_types.UOffsetTFlags.py_type(KRCharacterVoiceEn), 0)
def LocalizeCharProfileExcelAddHobbyKr(builder, HobbyKr): builder.PrependUOffsetTRelativeSlot(71, flatbuffers.number_types.UOffsetTFlags.py_type(HobbyKr), 0)
def LocalizeCharProfileExcelAddHobbyJp(builder, HobbyJp): builder.PrependUOffsetTRelativeSlot(72, flatbuffers.number_types.UOffsetTFlags.py_type(HobbyJp), 0)
def LocalizeCharProfileExcelAddHobbyTh(builder, HobbyTh): builder.PrependUOffsetTRelativeSlot(73, flatbuffers.number_types.UOffsetTFlags.py_type(HobbyTh), 0)
def LocalizeCharProfileExcelAddHobbyTw(builder, HobbyTw): builder.PrependUOffsetTRelativeSlot(74, flatbuffers.number_types.UOffsetTFlags.py_type(HobbyTw), 0)
def LocalizeCharProfileExcelAddHobbyEn(builder, HobbyEn): builder.PrependUOffsetTRelativeSlot(75, flatbuffers.number_types.UOffsetTFlags.py_type(HobbyEn), 0)
def LocalizeCharProfileExcelAddWeaponNameKr(builder, WeaponNameKr): builder.PrependUOffsetTRelativeSlot(76, flatbuffers.number_types.UOffsetTFlags.py_type(WeaponNameKr), 0)
def LocalizeCharProfileExcelAddWeaponDescKr(builder, WeaponDescKr): builder.PrependUOffsetTRelativeSlot(77, flatbuffers.number_types.UOffsetTFlags.py_type(WeaponDescKr), 0)
def LocalizeCharProfileExcelAddWeaponNameJp(builder, WeaponNameJp): builder.PrependUOffsetTRelativeSlot(78, flatbuffers.number_types.UOffsetTFlags.py_type(WeaponNameJp), 0)
def LocalizeCharProfileExcelAddWeaponDescJp(builder, WeaponDescJp): builder.PrependUOffsetTRelativeSlot(79, flatbuffers.number_types.UOffsetTFlags.py_type(WeaponDescJp), 0)
def LocalizeCharProfileExcelAddWeaponNameTh(builder, WeaponNameTh): builder.PrependUOffsetTRelativeSlot(80, flatbuffers.number_types.UOffsetTFlags.py_type(WeaponNameTh), 0)
def LocalizeCharProfileExcelAddWeaponDescTh(builder, WeaponDescTh): builder.PrependUOffsetTRelativeSlot(81, flatbuffers.number_types.UOffsetTFlags.py_type(WeaponDescTh), 0)
def LocalizeCharProfileExcelAddWeaponNameTw(builder, WeaponNameTw): builder.PrependUOffsetTRelativeSlot(82, flatbuffers.number_types.UOffsetTFlags.py_type(WeaponNameTw), 0)
def LocalizeCharProfileExcelAddWeaponDescTw(builder, WeaponDescTw): builder.PrependUOffsetTRelativeSlot(83, flatbuffers.number_types.UOffsetTFlags.py_type(WeaponDescTw), 0)
def LocalizeCharProfileExcelAddWeaponNameEn(builder, WeaponNameEn): builder.PrependUOffsetTRelativeSlot(84, flatbuffers.number_types.UOffsetTFlags.py_type(WeaponNameEn), 0)
def LocalizeCharProfileExcelAddWeaponDescEn(builder, WeaponDescEn): builder.PrependUOffsetTRelativeSlot(85, flatbuffers.number_types.UOffsetTFlags.py_type(WeaponDescEn), 0)
def LocalizeCharProfileExcelAddProfileIntroductionKr(builder, ProfileIntroductionKr): builder.PrependUOffsetTRelativeSlot(86, flatbuffers.number_types.UOffsetTFlags.py_type(ProfileIntroductionKr), 0)
def LocalizeCharProfileExcelAddProfileIntroductionJp(builder, ProfileIntroductionJp): builder.PrependUOffsetTRelativeSlot(87, flatbuffers.number_types.UOffsetTFlags.py_type(ProfileIntroductionJp), 0)
def LocalizeCharProfileExcelAddProfileIntroductionTh(builder, ProfileIntroductionTh): builder.PrependUOffsetTRelativeSlot(88, flatbuffers.number_types.UOffsetTFlags.py_type(ProfileIntroductionTh), 0)
def LocalizeCharProfileExcelAddProfileIntroductionTw(builder, ProfileIntroductionTw): builder.PrependUOffsetTRelativeSlot(89, flatbuffers.number_types.UOffsetTFlags.py_type(ProfileIntroductionTw), 0)
def LocalizeCharProfileExcelAddProfileIntroductionEn(builder, ProfileIntroductionEn): builder.PrependUOffsetTRelativeSlot(90, flatbuffers.number_types.UOffsetTFlags.py_type(ProfileIntroductionEn), 0)
def LocalizeCharProfileExcelAddCharacterSSRNewKr(builder, CharacterSSRNewKr): builder.PrependUOffsetTRelativeSlot(91, flatbuffers.number_types.UOffsetTFlags.py_type(CharacterSSRNewKr), 0)
def LocalizeCharProfileExcelAddCharacterSSRNewJp(builder, CharacterSSRNewJp): builder.PrependUOffsetTRelativeSlot(92, flatbuffers.number_types.UOffsetTFlags.py_type(CharacterSSRNewJp), 0)
def LocalizeCharProfileExcelAddCharacterSSRNewTh(builder, CharacterSSRNewTh): builder.PrependUOffsetTRelativeSlot(93, flatbuffers.number_types.UOffsetTFlags.py_type(CharacterSSRNewTh), 0)
def LocalizeCharProfileExcelAddCharacterSSRNewTw(builder, CharacterSSRNewTw): builder.PrependUOffsetTRelativeSlot(94, flatbuffers.number_types.UOffsetTFlags.py_type(CharacterSSRNewTw), 0)
def LocalizeCharProfileExcelAddCharacterSSRNewEn(builder, CharacterSSRNewEn): builder.PrependUOffsetTRelativeSlot(95, flatbuffers.number_types.UOffsetTFlags.py_type(CharacterSSRNewEn), 0)
def LocalizeCharProfileExcelEnd(builder): return builder.EndObject()
