# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MinigameTBGEncounterExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsMinigameTBGEncounterExcel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MinigameTBGEncounterExcel()
        x.Init(buf, n + offset)
        return x

    # MinigameTBGEncounterExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MinigameTBGEncounterExcel
    def EventContentId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # MinigameTBGEncounterExcel
    def UniqueId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # MinigameTBGEncounterExcel
    def AllThema(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # MinigameTBGEncounterExcel
    def ThemaIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MinigameTBGEncounterExcel
    def ThemaType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MinigameTBGEncounterExcel
    def ObjectType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MinigameTBGEncounterExcel
    def EnemyImagePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameTBGEncounterExcel
    def EnemyPrefabName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameTBGEncounterExcel
    def EnemyNameLocalize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameTBGEncounterExcel
    def OptionGroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # MinigameTBGEncounterExcel
    def RewardHide(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # MinigameTBGEncounterExcel
    def EncounterTitleLocalize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameTBGEncounterExcel
    def StoryImagePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameTBGEncounterExcel
    def BeforeStoryLocalize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameTBGEncounterExcel
    def BeforeStoryOption1Localize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameTBGEncounterExcel
    def BeforeStoryOption2Localize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameTBGEncounterExcel
    def BeforeStoryOption3Localize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameTBGEncounterExcel
    def AllyAttackLocalize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameTBGEncounterExcel
    def EnemyAttackLocalize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameTBGEncounterExcel
    def AttackDefenceLocalize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameTBGEncounterExcel
    def ClearStoryLocalize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameTBGEncounterExcel
    def DefeatStoryLocalize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameTBGEncounterExcel
    def RunawayStoryLocalize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def MinigameTBGEncounterExcelStart(builder): builder.StartObject(23)
def MinigameTBGEncounterExcelAddEventContentId(builder, EventContentId): builder.PrependInt64Slot(0, EventContentId, 0)
def MinigameTBGEncounterExcelAddUniqueId(builder, UniqueId): builder.PrependInt64Slot(1, UniqueId, 0)
def MinigameTBGEncounterExcelAddAllThema(builder, AllThema): builder.PrependBoolSlot(2, AllThema, 0)
def MinigameTBGEncounterExcelAddThemaIndex(builder, ThemaIndex): builder.PrependInt32Slot(3, ThemaIndex, 0)
def MinigameTBGEncounterExcelAddThemaType(builder, ThemaType): builder.PrependInt32Slot(4, ThemaType, 0)
def MinigameTBGEncounterExcelAddObjectType(builder, ObjectType): builder.PrependInt32Slot(5, ObjectType, 0)
def MinigameTBGEncounterExcelAddEnemyImagePath(builder, EnemyImagePath): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(EnemyImagePath), 0)
def MinigameTBGEncounterExcelAddEnemyPrefabName(builder, EnemyPrefabName): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(EnemyPrefabName), 0)
def MinigameTBGEncounterExcelAddEnemyNameLocalize(builder, EnemyNameLocalize): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(EnemyNameLocalize), 0)
def MinigameTBGEncounterExcelAddOptionGroupId(builder, OptionGroupId): builder.PrependInt64Slot(9, OptionGroupId, 0)
def MinigameTBGEncounterExcelAddRewardHide(builder, RewardHide): builder.PrependBoolSlot(10, RewardHide, 0)
def MinigameTBGEncounterExcelAddEncounterTitleLocalize(builder, EncounterTitleLocalize): builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(EncounterTitleLocalize), 0)
def MinigameTBGEncounterExcelAddStoryImagePath(builder, StoryImagePath): builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(StoryImagePath), 0)
def MinigameTBGEncounterExcelAddBeforeStoryLocalize(builder, BeforeStoryLocalize): builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(BeforeStoryLocalize), 0)
def MinigameTBGEncounterExcelAddBeforeStoryOption1Localize(builder, BeforeStoryOption1Localize): builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(BeforeStoryOption1Localize), 0)
def MinigameTBGEncounterExcelAddBeforeStoryOption2Localize(builder, BeforeStoryOption2Localize): builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(BeforeStoryOption2Localize), 0)
def MinigameTBGEncounterExcelAddBeforeStoryOption3Localize(builder, BeforeStoryOption3Localize): builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(BeforeStoryOption3Localize), 0)
def MinigameTBGEncounterExcelAddAllyAttackLocalize(builder, AllyAttackLocalize): builder.PrependUOffsetTRelativeSlot(17, flatbuffers.number_types.UOffsetTFlags.py_type(AllyAttackLocalize), 0)
def MinigameTBGEncounterExcelAddEnemyAttackLocalize(builder, EnemyAttackLocalize): builder.PrependUOffsetTRelativeSlot(18, flatbuffers.number_types.UOffsetTFlags.py_type(EnemyAttackLocalize), 0)
def MinigameTBGEncounterExcelAddAttackDefenceLocalize(builder, AttackDefenceLocalize): builder.PrependUOffsetTRelativeSlot(19, flatbuffers.number_types.UOffsetTFlags.py_type(AttackDefenceLocalize), 0)
def MinigameTBGEncounterExcelAddClearStoryLocalize(builder, ClearStoryLocalize): builder.PrependUOffsetTRelativeSlot(20, flatbuffers.number_types.UOffsetTFlags.py_type(ClearStoryLocalize), 0)
def MinigameTBGEncounterExcelAddDefeatStoryLocalize(builder, DefeatStoryLocalize): builder.PrependUOffsetTRelativeSlot(21, flatbuffers.number_types.UOffsetTFlags.py_type(DefeatStoryLocalize), 0)
def MinigameTBGEncounterExcelAddRunawayStoryLocalize(builder, RunawayStoryLocalize): builder.PrependUOffsetTRelativeSlot(22, flatbuffers.number_types.UOffsetTFlags.py_type(RunawayStoryLocalize), 0)
def MinigameTBGEncounterExcelEnd(builder): return builder.EndObject()
