# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MultiFloorRaidSeasonManageExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsMultiFloorRaidSeasonManageExcel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MultiFloorRaidSeasonManageExcel()
        x.Init(buf, n + offset)
        return x

    # MultiFloorRaidSeasonManageExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MultiFloorRaidSeasonManageExcel
    def SeasonId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # MultiFloorRaidSeasonManageExcel
    def LobbyEnterScenario(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MultiFloorRaidSeasonManageExcel
    def ShowLobbyBanner(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # MultiFloorRaidSeasonManageExcel
    def SeasonStartDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MultiFloorRaidSeasonManageExcel
    def SeasonEndDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MultiFloorRaidSeasonManageExcel
    def SettlementEndDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MultiFloorRaidSeasonManageExcel
    def OpenRaidBossGroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MultiFloorRaidSeasonManageExcel
    def EnterScenarioKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MultiFloorRaidSeasonManageExcel
    def LobbyImgPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MultiFloorRaidSeasonManageExcel
    def LevelImgPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def MultiFloorRaidSeasonManageExcelStart(builder): builder.StartObject(10)
def MultiFloorRaidSeasonManageExcelAddSeasonId(builder, SeasonId): builder.PrependInt64Slot(0, SeasonId, 0)
def MultiFloorRaidSeasonManageExcelAddLobbyEnterScenario(builder, LobbyEnterScenario): builder.PrependUint32Slot(1, LobbyEnterScenario, 0)
def MultiFloorRaidSeasonManageExcelAddShowLobbyBanner(builder, ShowLobbyBanner): builder.PrependBoolSlot(2, ShowLobbyBanner, 0)
def MultiFloorRaidSeasonManageExcelAddSeasonStartDate(builder, SeasonStartDate): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(SeasonStartDate), 0)
def MultiFloorRaidSeasonManageExcelAddSeasonEndDate(builder, SeasonEndDate): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(SeasonEndDate), 0)
def MultiFloorRaidSeasonManageExcelAddSettlementEndDate(builder, SettlementEndDate): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(SettlementEndDate), 0)
def MultiFloorRaidSeasonManageExcelAddOpenRaidBossGroupId(builder, OpenRaidBossGroupId): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(OpenRaidBossGroupId), 0)
def MultiFloorRaidSeasonManageExcelAddEnterScenarioKey(builder, EnterScenarioKey): builder.PrependUint32Slot(7, EnterScenarioKey, 0)
def MultiFloorRaidSeasonManageExcelAddLobbyImgPath(builder, LobbyImgPath): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(LobbyImgPath), 0)
def MultiFloorRaidSeasonManageExcelAddLevelImgPath(builder, LevelImgPath): builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(LevelImgPath), 0)
def MultiFloorRaidSeasonManageExcelEnd(builder): return builder.EndObject()
