# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PickupDuplicateBonusExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPickupDuplicateBonusExcel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PickupDuplicateBonusExcel()
        x.Init(buf, n + offset)
        return x

    # PickupDuplicateBonusExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PickupDuplicateBonusExcel
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # PickupDuplicateBonusExcel
    def ShopCategoryType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # PickupDuplicateBonusExcel
    def ShopId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # PickupDuplicateBonusExcel
    def PickupCharacterId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # PickupDuplicateBonusExcel
    def RewardParcelType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # PickupDuplicateBonusExcel
    def RewardParcelId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # PickupDuplicateBonusExcel
    def RewardParcelAmount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def PickupDuplicateBonusExcelStart(builder): builder.StartObject(7)
def PickupDuplicateBonusExcelAddId(builder, Id): builder.PrependInt64Slot(0, Id, 0)
def PickupDuplicateBonusExcelAddShopCategoryType(builder, ShopCategoryType): builder.PrependInt32Slot(1, ShopCategoryType, 0)
def PickupDuplicateBonusExcelAddShopId(builder, ShopId): builder.PrependInt64Slot(2, ShopId, 0)
def PickupDuplicateBonusExcelAddPickupCharacterId(builder, PickupCharacterId): builder.PrependInt64Slot(3, PickupCharacterId, 0)
def PickupDuplicateBonusExcelAddRewardParcelType(builder, RewardParcelType): builder.PrependInt32Slot(4, RewardParcelType, 0)
def PickupDuplicateBonusExcelAddRewardParcelId(builder, RewardParcelId): builder.PrependInt64Slot(5, RewardParcelId, 0)
def PickupDuplicateBonusExcelAddRewardParcelAmount(builder, RewardParcelAmount): builder.PrependInt64Slot(6, RewardParcelAmount, 0)
def PickupDuplicateBonusExcelEnd(builder): return builder.EndObject()
