# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ScenarioResourceInfoExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsScenarioResourceInfoExcel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ScenarioResourceInfoExcel()
        x.Init(buf, n + offset)
        return x

    # ScenarioResourceInfoExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ScenarioResourceInfoExcel
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ScenarioResourceInfoExcel
    def ScenarioModeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ScenarioResourceInfoExcel
    def VideoId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ScenarioResourceInfoExcel
    def BgmId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ScenarioResourceInfoExcel
    def AudioName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioResourceInfoExcel
    def SpinePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioResourceInfoExcel
    def Ratio(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ScenarioResourceInfoExcel
    def LobbyAniPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioResourceInfoExcel
    def MovieCGPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioResourceInfoExcel
    def LocalizeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ScenarioResourceInfoExcelStart(builder): builder.StartObject(10)
def ScenarioResourceInfoExcelAddId(builder, Id): builder.PrependInt64Slot(0, Id, 0)
def ScenarioResourceInfoExcelAddScenarioModeId(builder, ScenarioModeId): builder.PrependInt64Slot(1, ScenarioModeId, 0)
def ScenarioResourceInfoExcelAddVideoId(builder, VideoId): builder.PrependInt64Slot(2, VideoId, 0)
def ScenarioResourceInfoExcelAddBgmId(builder, BgmId): builder.PrependInt64Slot(3, BgmId, 0)
def ScenarioResourceInfoExcelAddAudioName(builder, AudioName): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(AudioName), 0)
def ScenarioResourceInfoExcelAddSpinePath(builder, SpinePath): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(SpinePath), 0)
def ScenarioResourceInfoExcelAddRatio(builder, Ratio): builder.PrependInt32Slot(6, Ratio, 0)
def ScenarioResourceInfoExcelAddLobbyAniPath(builder, LobbyAniPath): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(LobbyAniPath), 0)
def ScenarioResourceInfoExcelAddMovieCGPath(builder, MovieCGPath): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(MovieCGPath), 0)
def ScenarioResourceInfoExcelAddLocalizeId(builder, LocalizeId): builder.PrependUint32Slot(9, LocalizeId, 0)
def ScenarioResourceInfoExcelEnd(builder): return builder.EndObject()
