# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ServiceActionExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsServiceActionExcel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ServiceActionExcel()
        x.Init(buf, n + offset)
        return x

    # ServiceActionExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ServiceActionExcel
    def ServiceActionType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ServiceActionExcel
    def IsLegacy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ServiceActionExcel
    def GoodsId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def ServiceActionExcelStart(builder): builder.StartObject(3)
def ServiceActionExcelAddServiceActionType(builder, ServiceActionType): builder.PrependInt32Slot(0, ServiceActionType, 0)
def ServiceActionExcelAddIsLegacy(builder, IsLegacy): builder.PrependBoolSlot(1, IsLegacy, 0)
def ServiceActionExcelAddGoodsId(builder, GoodsId): builder.PrependInt64Slot(2, GoodsId, 0)
def ServiceActionExcelEnd(builder): return builder.EndObject()
