# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StageFileRefreshSettingExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsStageFileRefreshSettingExcel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StageFileRefreshSettingExcel()
        x.Init(buf, n + offset)
        return x

    # StageFileRefreshSettingExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StageFileRefreshSettingExcel
    def GroundId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # StageFileRefreshSettingExcel
    def ForceSave(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def StageFileRefreshSettingExcelStart(builder): builder.StartObject(2)
def StageFileRefreshSettingExcelAddGroundId(builder, GroundId): builder.PrependInt64Slot(0, GroundId, 0)
def StageFileRefreshSettingExcelAddForceSave(builder, ForceSave): builder.PrependBoolSlot(1, ForceSave, 0)
def StageFileRefreshSettingExcelEnd(builder): return builder.EndObject()
