# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SystemMailExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSystemMailExcel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SystemMailExcel()
        x.Init(buf, n + offset)
        return x

    # SystemMailExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SystemMailExcel
    def MailType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SystemMailExcel
    def ExpiredDay(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # SystemMailExcel
    def Sender(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SystemMailExcel
    def Comment(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SystemMailExcelStart(builder): builder.StartObject(4)
def SystemMailExcelAddMailType(builder, MailType): builder.PrependInt32Slot(0, MailType, 0)
def SystemMailExcelAddExpiredDay(builder, ExpiredDay): builder.PrependInt64Slot(1, ExpiredDay, 0)
def SystemMailExcelAddSender(builder, Sender): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(Sender), 0)
def SystemMailExcelAddComment(builder, Comment): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(Comment), 0)
def SystemMailExcelEnd(builder): return builder.EndObject()
