# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TacticTimeAttackSimulatorConfigExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTacticTimeAttackSimulatorConfigExcel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TacticTimeAttackSimulatorConfigExcel()
        x.Init(buf, n + offset)
        return x

    # TacticTimeAttackSimulatorConfigExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TacticTimeAttackSimulatorConfigExcel
    def Order(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # TacticTimeAttackSimulatorConfigExcel
    def Repeat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # TacticTimeAttackSimulatorConfigExcel
    def PresetGroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # TacticTimeAttackSimulatorConfigExcel
    def AttackStrikerNum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # TacticTimeAttackSimulatorConfigExcel
    def AttackSpecialNum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # TacticTimeAttackSimulatorConfigExcel
    def GeasId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def TacticTimeAttackSimulatorConfigExcelStart(builder): builder.StartObject(6)
def TacticTimeAttackSimulatorConfigExcelAddOrder(builder, Order): builder.PrependInt64Slot(0, Order, 0)
def TacticTimeAttackSimulatorConfigExcelAddRepeat(builder, Repeat): builder.PrependInt64Slot(1, Repeat, 0)
def TacticTimeAttackSimulatorConfigExcelAddPresetGroupId(builder, PresetGroupId): builder.PrependInt64Slot(2, PresetGroupId, 0)
def TacticTimeAttackSimulatorConfigExcelAddAttackStrikerNum(builder, AttackStrikerNum): builder.PrependInt64Slot(3, AttackStrikerNum, 0)
def TacticTimeAttackSimulatorConfigExcelAddAttackSpecialNum(builder, AttackSpecialNum): builder.PrependInt64Slot(4, AttackSpecialNum, 0)
def TacticTimeAttackSimulatorConfigExcelAddGeasId(builder, GeasId): builder.PrependInt64Slot(5, GeasId, 0)
def TacticTimeAttackSimulatorConfigExcelEnd(builder): return builder.EndObject()
